version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/go/src/api
    ports:
      - 8080:8080
    tty: true
    command: air
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    env_file:
      - ./docker/db/.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3305:3306"
    security_opt:
      - seccomp:unconfined

  test-db:
    image: mysql:8.0
    env_file:
      - ./docker/testdb/.env
    volumes:
      - ./docker/testdb/data:/var/lib/mysql
      - ./docker/testdb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined